package com.edu.entry;

import java.util.Date;

public class Order {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.id
     *
     * @mbg.generated Fri Mar 20 13:40:12 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.creation_time
     *
     * @mbg.generated Fri Mar 20 13:40:12 CST 2020
     */
    private Date creationTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.amount
     *
     * @mbg.generated Fri Mar 20 13:40:12 CST 2020
     */
    private Integer amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.money
     *
     * @mbg.generated Fri Mar 20 13:40:12 CST 2020
     */
    private Float money;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.mode_payment
     *
     * @mbg.generated Fri Mar 20 13:40:12 CST 2020
     */
    private String modePayment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.order_status
     *
     * @mbg.generated Fri Mar 20 13:40:12 CST 2020
     */
    private String orderStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.address
     *
     * @mbg.generated Fri Mar 20 13:40:12 CST 2020
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.tel
     *
     * @mbg.generated Fri Mar 20 13:40:12 CST 2020
     */
    private String tel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.tracking_number
     *
     * @mbg.generated Fri Mar 20 13:40:12 CST 2020
     */
    private Integer trackingNumber;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.id
     *
     * @return the value of order.id
     *
     * @mbg.generated Fri Mar 20 13:40:12 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.id
     *
     * @param id the value for order.id
     *
     * @mbg.generated Fri Mar 20 13:40:12 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.creation_time
     *
     * @return the value of order.creation_time
     *
     * @mbg.generated Fri Mar 20 13:40:12 CST 2020
     */
    public Date getCreationTime() {
        return creationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.creation_time
     *
     * @param creationTime the value for order.creation_time
     *
     * @mbg.generated Fri Mar 20 13:40:12 CST 2020
     */
    public void setCreationTime(Date creationTime) {
        this.creationTime = creationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.amount
     *
     * @return the value of order.amount
     *
     * @mbg.generated Fri Mar 20 13:40:12 CST 2020
     */
    public Integer getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.amount
     *
     * @param amount the value for order.amount
     *
     * @mbg.generated Fri Mar 20 13:40:12 CST 2020
     */
    public void setAmount(Integer amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.money
     *
     * @return the value of order.money
     *
     * @mbg.generated Fri Mar 20 13:40:12 CST 2020
     */
    public Float getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.money
     *
     * @param money the value for order.money
     *
     * @mbg.generated Fri Mar 20 13:40:12 CST 2020
     */
    public void setMoney(Float money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.mode_payment
     *
     * @return the value of order.mode_payment
     *
     * @mbg.generated Fri Mar 20 13:40:12 CST 2020
     */
    public String getModePayment() {
        return modePayment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.mode_payment
     *
     * @param modePayment the value for order.mode_payment
     *
     * @mbg.generated Fri Mar 20 13:40:12 CST 2020
     */
    public void setModePayment(String modePayment) {
        this.modePayment = modePayment == null ? null : modePayment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.order_status
     *
     * @return the value of order.order_status
     *
     * @mbg.generated Fri Mar 20 13:40:12 CST 2020
     */
    public String getOrderStatus() {
        return orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.order_status
     *
     * @param orderStatus the value for order.order_status
     *
     * @mbg.generated Fri Mar 20 13:40:12 CST 2020
     */
    public void setOrderStatus(String orderStatus) {
        this.orderStatus = orderStatus == null ? null : orderStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.address
     *
     * @return the value of order.address
     *
     * @mbg.generated Fri Mar 20 13:40:12 CST 2020
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.address
     *
     * @param address the value for order.address
     *
     * @mbg.generated Fri Mar 20 13:40:12 CST 2020
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.tel
     *
     * @return the value of order.tel
     *
     * @mbg.generated Fri Mar 20 13:40:12 CST 2020
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.tel
     *
     * @param tel the value for order.tel
     *
     * @mbg.generated Fri Mar 20 13:40:12 CST 2020
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.tracking_number
     *
     * @return the value of order.tracking_number
     *
     * @mbg.generated Fri Mar 20 13:40:12 CST 2020
     */
    public Integer getTrackingNumber() {
        return trackingNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.tracking_number
     *
     * @param trackingNumber the value for order.tracking_number
     *
     * @mbg.generated Fri Mar 20 13:40:12 CST 2020
     */
    public void setTrackingNumber(Integer trackingNumber) {
        this.trackingNumber = trackingNumber;
    }
}